services:
  db:
    image: postgres:15-alpine
    container_name: postgres-rede-social
    environment:
      POSTGRES_DB: redesocial_db
      POSTGRES_USER: Qdop
      POSTGRES_PASSWORD: Qdop123
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: spring-app-rede-social
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=redesocial_db
      - DB_USER=Qdop
      - DB_PASS=Qdop123
      - JWT_SECRET=${JWT_SECRET}